name: Troygrade
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu
          - os: macos-latest
            rust_target: x86_64-apple-darwin
          - os: macos-latest
            rust_target: aarch64-apple-darwin
          - os: windows-latest
            rust_target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # for projects that use labels and PRs,
      # try https://github.com/mikepenz/release-changelog-builder-action instead
      # TODO: use API to collect commit messages
      - name: Build Changelog
        id: build_changelog
        run: echo "changelog=- ADD CHANGELOG" >> $GITHUB_OUTPUT

      - name: Install npm (windows only)
        uses: actions/setup-node@v4

      - name: Install Rust (Stable)
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file webkit2gtk-4.0 libssl-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Install app dependencies from lockfile and build web (npm)
        run: npm install

      - name: Build the app
        uses: tauri-apps/tauri-action@v0.5.1
        # if u get Error: Resource not accessible by integration
        # go to repository Settings => Action => General => Workflow permissions => Switch to Read and Write permisions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          # tauri-action replaces \_\_VERSION\_\_ with the app version
          tagName: ${{ github.ref_name }}
          releaseName: "Troygrade for desktop v__VERSION__"
          releaseBody: |
            ${{steps.build_changelog.outputs.changelog}}
            See the assets to download this version and install.
          releaseDraft: true
          prerelease: false
